package com.example.propertymanagement.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

import java.time.LocalDate;

/**
 * Represents a booking entity in the property management system.
 * This class is used to store information about bookings made by customers for properties.
 * It is mapped to a database table using JPA annotations.
 *
 * @author Your Name
 * @version 1.0
 * @since 2023-10-01
 */
@Data
@Entity
public class Booking {

    /**
     * The unique identifier for the booking.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The ID of the property associated with this booking.
     * This field establishes a relationship between the booking and the property.
     */
    private Long propertyId;

    /**
     * The date on which the booking was made.
     * This field represents the booking date in the format YYYY-MM-DD.
     */
    private LocalDate bookingDate;

    /**
     * The name of the customer who made the booking.
     * This field stores the full name of the customer.
     */
    private String customerName;

    /**
     * The email address of the customer who made the booking.
     * This field is used for communication and identification purposes.
     */
    private String customerEmail;
}