package com.example.propertymanagement.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

/**
 * Represents an inquiry entity in the property management system.
 * This class is used to store information about inquiries made by customers regarding properties.
 * It is mapped to a database table using JPA annotations.
 *
 * @author Your Name
 * @version 1.0
 * @since 2023-10-01
 */
@Data
@Entity
public class Inquiry {

    /**
     * The unique identifier for the inquiry.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The ID of the property associated with this inquiry.
     * This field establishes a relationship between the inquiry and the property.
     */
    private Long propertyId;

    /**
     * The name of the customer who made the inquiry.
     * This field stores the full name of the customer.
     */
    private String customerName;

    /**
     * The email address of the customer who made the inquiry.
     * This field is used for communication and identification purposes.
     */
    private String customerEmail;

    /**
     * The message or details provided by the customer in the inquiry.
     * This field contains the customer's questions or comments about the property.
     */
    private String message;
}